<?php
declare(strict_types=1);

namespace Daylog\Tests\Integration\Application\UseCases\Entries;

use Codeception\Test\Unit;
use Daylog\Tests\Support\Helper\EntriesSeeding;

/**
 * Base TestCase for Entry integration tests (shared across UC-1..UC-5).
 *
 * Purpose:
 * Provide deterministic seeding helpers for integration tests wired against the real DB.
 * Encapsulates pushing prepared rows from UC datasets into the SQL-backed storage.
 *
 * Mechanics:
 * - Accepts UC dataset shape with 'rows';
 * - Calls EntriesSeeding::intoDb() to populate the real DB table;
 * - Ensures integration tests start from a consistent baseline state.
 *
 * Notes:
 * - Intended to be extended by concrete integration tests for Add/Get/Update/Delete use cases.
 */
abstract class BaseEntryUseCaseIntegrationTest extends Unit
{
    /**
     * Seed DB with rows from a dataset (UC-specific builder).
     *
     * Purpose:
     * Provide deterministic baseline data for integration tests by seeding
     * the actual database table with prepared rows.
     *
     * Mechanics:
     * - Extract 'rows' from the provided dataset (generated by a UC Dataset builder);
     * - Pass rows to EntriesSeeding::intoDb() to populate the DB;
     * - Keeps integration tests reproducible and isolated.
     *
     * @param array{
     *     rows: array<int, array{
     *         id: string,
     *         title: string,
     *         body: string,
     *         date: string,
     *         createdAt: string,
     *         updatedAt: string
     *     }>
     * } $dataset Deterministic dataset containing prepared DB rows.
     *
     * @return void
     */
    protected function seedFromDataset(array $dataset): void
    {
        $rows = $dataset['rows'];
        EntriesSeeding::intoDb($rows);
    }
}
